.\"
.\" This manual page is written by NAKANO Takeo <nakano@webmasters.gr.jp>
.\"
.TH TTYREC 1
.SH NAME
ttyrec \- a tty recorder
.SH SYNOPSIS
.br
.B ttyrec
.I "[\-a][\-u] [file]"
.br
.SH DESCRIPTION
.B Ttyrec
is a tty recorder.
It is a derivative of
.BR script (1)
command for recording timing information with microsecond accuracy as well.
It can record emacs -nw, vi, lynx, or any programs running on tty.
.PP
.B Ttyrec
invokes a shell and records the session until the shell exits.
Recorded data can be played back with
.BR ttyplay (1).
If the argument
.I file
is given, the session will be recorded in that file.
Otherwise,
.I ttyrecord
is used as default.
.SH OPTIONS
.TP
.B \-a
Append the output to
.I file
or
.IR ttyrecord ,
rather than overwriting it.
.TP
.B \-u
With this option,
.B ttyrec
automatically calls
.BR uudecode (1)
and saves its output when uuencoded data appear on the session.
It allow you to transfer files from remote host.
You can call
.B ttyrec
with this option, login to the remote host
and invoke
.BR uuencode (1)
on it for the file you want to transfer.
.TP
.BI \-e " command"
Invoke 
.I command
when ttyrec starts.


.SH ENVIRONMENT
.TP
.I SHELL
If the variable
.I SHELL
exists, the shell forked by
.B ttyrec
will be that shell.
If it's not set,
the Bourne shell is assumed.
(Most shells set this variable automatically).
.SH "SEE ALSO"
.BR script (1),
.BR ttyplay (1),
.BR ttytime (1),
.BR uuencode (1),
.BR uudecode (1)

